- name: Install required deps
  apt: name=mysql-server-5.6 state=present

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  mysql_user:
    check_implicit_admin=True
    name=root
    login_user=root
    login_password={{ mysql_password }}
    password={{ mysql_password }}

- name: delete anonymous MySQL server user for localhost
  mysql_user: 
    user=""
    state=absent
    login_user=root
    login_password={{ mysql_password }}

- name: remove the MySQL test database
  mysql_db:
    db=test
    state=absent
    login_user=root
    login_password={{ mysql_password }}