- name: Install required deps
  apt: name={{item}} state=present
  with_items:
    - mysql-server
    - python-mysqldb

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql.password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=../common/templates/mysql.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: delete anonymous MySQL server user for localhost
  mysql_user: 
    user=""
    state=absent
    login_user=root
    login_password={{ mysql.password }}

- name: remove the MySQL test database
  mysql_db:
    db=test
    state=absent
    login_user=root
    login_password={{ mysql.password }}