- name: add phileas db
  mysql_db:
    db=phileas
    state=present

- name: add phileas user
  mysql_user: 
    user={{ phileas.mysql.username }}
    password={{ phileas.mysql.password }}
    priv=phileas.*:ALL
    state=present

- name: add additional dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - vlc

- name: install youtube-dl
  pip: name=youtube_dl state=present extra_args=--upgrade

- template: src=../common/templates/phileas.ini.j2 dest=/etc/phileas.ini